// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxxlfnthnyozgsgicser.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4eGxmbnRobnlvemdzZ2ljc2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzODE0NzcsImV4cCI6MjA1OTk1NzQ3N30.NRWiTBjSoLmFZFX2kmQiIjise97d4Ce5WjvoUGn6uwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);